### PR TITLE
More instances for `Product`. Missing dependency.

### PR DESCRIPTION
**Pull request by zrho**

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! Is `MonadPlus` valid too?

**Comment by zrho** [comment]
Intuitively, yes, since everything just happens pointwise. I'll have a
closer look at it tomorrow.

**Comment by zrho** [comment]
If I haven't missed something, `MonadPlus` appears to be valid, too:

``` purescript
  (product a a' <|> product b b') >>= f
= product (a <|> b) (a' <|> b') >>= f
= product ((a <|> b) >>= (fstP <<< f)) ((a' <|> b') >>= (sndP <<< f))
= product ((a >>= (fstP <<< f)) <|> (b >>= (fstP <<< f))) ((a' >>= (sndP <<< f)) <|> (b' >>= (sndP <<< f)))
= product (a >>= (fstP <<< f)) (a' >>= (sndP <<< f)) <|> product (b >>= (fstP <<< f)) (b' >>= (sndP <<< f))
= (product a a' >>= f) <|> (product b b' >>= f)
```

(`fstP` is `fst <<< runProduct` and `snd` analogous)

**Comment by paf31** [comment]
👍 @garyb Can we please include this when we bump to 1.0?

**Comment by garyb** [comment]
Sure thing. This repo becomes deprecated then in favour of `purescript-functor-products`, I'll re-apply the changes there.

**Comment by paf31** [comment]
Ah, ok.

**Pull request merged**
